source/neuropod/bindings/python_bindings.cc, source/neuropod/tests/test_serialization.cc, source/python/neuropod/tests/test_serialization.py
Previously, the python bindings did not correctly set the numpy array type for string tensors with zero elements.
This PR adds a fix along with additional tests.
Added some new cases to the existing serialization tests:
1. A C++ test for string tensors with zero elements
2. A Python test for string tensors with zero elements
Before the fix in this PR, the C++ test passed, but the python one failed (implying an issue in the python bindings). With the fix, both tests pass.
=> [Bindings] Fix a type issue for string tensors of zero elements

source/deps/BUILD.pybind11, source/deps/BUILD.python, source/neuropod/backends/python_bridge/BUILD
This change splits the python bazel dependency into a `python_hdrs` target and a `python` target.
This lets us build the python bindings against just the headers (without linking against python) while linking the pythonbridge backend against python.
Fixes #387
CI + 
Verification that `neuropod_native.so` doesn't depend on Python, but `libneuropod_pythonbridge_backend.so` does
Linux:
```
$ ldd neuropod_native.so | grep libpython | wc -l
0
$ ldd libneuropod_pythonbridge_backend.so | grep libpython | wc -l
1
```
Mac:
```
$ otool -L neuropod_native.so | grep Python.framework | wc -l
0
$ otool -L libneuropod_pythonbridge_backend.so | grep Python.framework | wc -l
1
```
=> [Build] Split Python dependency into headers and libs

source/python/neuropod/backends/python/executor.py, source/python/neuropod/loader.py, source/python/neuropod/tests/test_python_packaging.py
Move the `sys.argv` fix for embedded python interpreters (originally added in #375) from `loader.py` to `executor.py` in the python backend.
This is necessary because the C++ PythonBridge uses the python executor directly and bypasses `loader.py`.
More details in #374
Added a new test that confirms `sys.argv` is available from within python models.
_Note: This description was edited by @VivekPanyam to add details and improve clarity_
=> Move the embedded python interpreter sys.argv fix into the python backend

source/python/neuropod/tests/custom_ops/pytorch/test_pytorch_custom_ops.py, source/python/neuropod/utils/packaging_utils.py
Previously, when packaging a model multiple times, the hash of the output package could change even if the input did not (e.g. all the files contained in the package had the same hashes).
This was mostly because the output Neuropod package (which is a zipfile) stored timestamps of all the included files. It was also possible that we'd add files to the zip in different orders (because `os.walk` doesn't guarantee an order).
This PR sets the timestamp of all included files to a constant and also ensures that we always add the files in the same order.
Added a test to package a model twice and compare the `sha256` of the output. Also confirmed consistent hashes on a model internally.
=> Ensure consistent output hashes when packaging the same model

build/ci/lint.sh, source/python/setup.py, tools/autofix.sh, tools/lint.sh
The `typing` module is available within CPython >= 3.5 so we don't need to depend on the pip package.
See https://github.com/python/typing/issues/739 for more details
Note: This PR also modifies some lint scripts to ensure that `setup.py` is covered by the linter.
CI
=> [Build] Remove typing dependency for python >=3.5

source/neuropod/bindings/c/c_api.h, source/neuropod/bindings/c/np_status.h, source/neuropod/bindings/c/np_tensor.h, source/neuropod/bindings/c/np_tensor_allocator.h, source/neuropod/bindings/c/np_tensor_spec.h, source/neuropod/bindings/c/np_valuemap.h
An initial interface for a Neuropod C API.
=> [C API] Initial interface proposal

source/neuropod/bindings/c/BUILD, source/neuropod/bindings/c/c_api.cc, source/neuropod/bindings/c/c_api_internal.h, source/neuropod/bindings/c/np_status.cc, source/neuropod/bindings/c/np_status_internal.h, source/neuropod/bindings/c/np_tensor.cc, source/neuropod/bindings/c/np_tensor_allocator.cc, source/neuropod/bindings/c/np_tensor_allocator_internal.h, source/neuropod/bindings/c/np_tensor_internal.h, source/neuropod/bindings/c/np_valuemap.cc, source/neuropod/bindings/c/np_valuemap_internal.h, source/neuropod/tests/BUILD, source/neuropod/tests/test_c_api.cc, tools/autofix.sh
An initial basic implementation of a C API for Neuropod.
Added a test that loads a model, runs inference, and verifies the output. More unit tests and integration tests should be added in the future
=> [C API] Initial implementation

source/neuropod/bindings/java/README.md, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/Dimension.java, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/LibraryLoader.java, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/NativeClass.java, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/Neuropod.java, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/NeuropodDevice.java, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/NeuropodJNIException.java, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/NeuropodTensor.java, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/NeuropodTensorAllocator.java, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/RuntimeOptions.java, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/TensorSpec.java, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/TensorType.java, source/neuropod/bindings/java/src/main/resources/META-INF/MANIFEST.MF
The Java API Interface for Neuropod Java API.
The NeuropodNativeTensor class will be implemented as the following: It can be created by both C++ side(as inference result) and Java side. It has a private field buffer. For the objects created by C++ side, the buffer is wrapped from the raw memory pointer from the C++ side tensor. For the objects created by Java side, the buffer is a direct native bytebuffer from the Java side. The C++ tensor is created from the Java bytebuffer's memory. User won't tell the difference between these two types of NeuropodNativeTensor, unless they try to convert it to a pure Java tensor NeuropodJavaTensor. NeuropodNativeTensor created by the C++ side will have to trigger a copy to make the memory section is allocated by the Java side.
=> [Java API] Neuropod Java API Interface Proposal

source/neuropod/bindings/python_bindings.cc, source/python/neuropod/tests/test_python_packaging.py
Ensures that all numpy arrays passed to C++ Neuropod code are contiguous and aligned.
Fixes #384
Added a test. The test did not pass before the fix in `python_bindings.cc` and it does pass after the fix.
=> [Python Bindings] Ensure arrays are contiguous and aligned

source/neuropod/internal/backend_registration.cc
Our intended error message when a backend is not found is pretty clear:
https://github.com/uber/neuropod/blob/4f5764af8f29d1ca241f9576cf4ea5bae5c025dd/source/neuropod/internal/backend_registration.cc#L248-L253
but unfortunately, we hit another error first (`Loading the default backend for type '{}' failed. Error from dlopen: {}`)
This has come up in several issues: https://github.com/uber/neuropod/issues/383, https://github.com/uber/neuropod/issues/387#issuecomment-645681546, https://github.com/uber/neuropod/issues/403#issuecomment-667234221
This PR changes some of these intermediate error messages to TRACE output instead.
CI
=> Improve error messages when a backend is not found

source/neuropod/bindings/java/BUILD
#405 breaks the macOS build. This PR fixes it
CI
=> [Build] Fix macOS build broken by #405

.travis.yml, build/ci/travis_build.sh, build/ci_matrix.py
Modify Travis CI caching so it doesn't require the use of secrets during the build. This makes it work on PRs that originate outside the repo.
CI
=> [Build] Improve Travis CI caching

source/neuropod/bindings/c/README.md, source/neuropod/bindings/c/c_api.cc, source/neuropod/bindings/c/c_api.h, source/neuropod/bindings/c/np_tensor.cc, source/neuropod/bindings/c/np_tensor.h, source/neuropod/tests/BUILD, source/neuropod/tests/test_c_api.c, source/neuropod/tests/test_c_api.cc
Continue with basic implementation of a C API for Neuropod. Issue #407 
Added a test that loads a model and fails, runs inference successfully and fails, and verifies the name and platform.
=> [C API] Continue implementation

source/neuropod/bindings/c/c_api.cc, source/neuropod/bindings/c/c_api.h, source/neuropod/bindings/c/np_tensor.cc, source/neuropod/tests/test_c_api.c
Continue with basic implementation of a C API for Neuropod. Issue #407
Added test for input and output tensors.
=> [C API] NP_GetType implementation

build/ci/install_lint_deps.sh
There was a new [major](https://github.com/psf/black/releases/tag/20.8b0) [release](https://github.com/psf/black/releases/tag/20.8b1) of Black this morning that changed some formatting behavior. 
This pins to a previous release until a non-beta v20 release of black is published
CI
=> [Build] Pin Black to v19.10b0

source/neuropod/bindings/c/np_tensor.cc, source/neuropod/tests/test_c_api.c, tools/autofix.sh
Continue with basic implementation of a C API for Neuropod. Issue #407
Added test that test returned values of number of dims and data in dims array.
=> [C API] NP_GetDims implementation

source/neuropod/bindings/java/BUILD, source/neuropod/bindings/java/src/test/java/com/uber/neuropod/DifferentFeaturesTest.java, source/neuropod/bindings/java/src/test/java/com/uber/neuropod/NeuropodAdditionTest.java, source/neuropod/bindings/java/src/test/java/com/uber/neuropod/TFAdditionTest.java, source/neuropod/bindings/java/src/test/java/com/uber/neuropod/TensorSpecTest.java, source/neuropod/bindings/java/src/test/java/com/uber/neuropod/TorchscriptAdditionTest.java
NeuropodAdditionTest can be improved to be generic test that works with TF and Torchscript addition models. Class NeuropodAdditionTest implements tests, derived classes for TF and Torchscript only prepare test environment and specify appropriate model config.
Build and then run Java tests:
python ../build/run_bazel_tests.py --lang java
and then all tests
build/test.sh
=> [Java API] Improve Java Addition Model Test

source/neuropod/bindings/java/src/main/java/com/uber/neuropod/NeuropodTensor.java, source/neuropod/bindings/java/src/main/native/com_uber_neuropod_NeuropodTensor.cc, source/neuropod/bindings/java/src/main/native/com_uber_neuropod_NeuropodTensor.h, source/neuropod/bindings/java/src/main/native/utils.cc, source/neuropod/bindings/java/src/main/native/utils.h, source/neuropod/bindings/java/src/main/native/utils_impl.h, source/neuropod/bindings/java/src/test/java/com/uber/neuropod/NeuropodAdditionTest.java
This PR includes complete implementation of Neuropod Tensor class, including support of STRING_TENSOR.
Note: that next PR will complete Neuropod Allocator that includes operations for STRING_TENSOR type.
Run Java tests
python ../build/run_bazel_tests.py --lang java
=> [Java API] Complete NeuropodTensor implementation

source/neuropod/bindings/java/README.md
Example incorrectly demonstrated using of a Java try-with block for Tensor allocations. 
Fix it and leave note that try-with is safe for multiple allocations even if one of it throws exception. 
N/A
=> Fix Java API example

source/neuropod/multiprocess/shm_tensor.hh, source/neuropod/tests/BUILD, source/neuropod/tests/test_ope_multiple_instances.cc
#397 describes a segfault that happens in certain cases when creating several string tensors and using OPE with multiple models across threads.
This PR implements a test that can reproduce the segfault a very high percentage of the time along with a fix for the root cause of the issue.
This line was the root cause of the issue:
https://github.com/uber/neuropod/blob/14a7e67edfe61930e123582be26075b9efcbe8f7/source/neuropod/multiprocess/shm_tensor.hh#L195-L196
We were not storing the unique_ptr created by `make_unique` so the destructor was immediately called. The reason this didn't cause visible issues in all cases has to do with how caching of shared memory blocks is implemented.
When `block` is destroyed in the code above, the underlying shared memory block is returned to an in-process …
=> Fix a bug with string tensors and OPE

source/bazel/cc.bzl, source/neuropod/internal/BUILD, source/neuropod/internal/backend_registration.cc, source/neuropod/internal/config_utils.cc, source/neuropod/internal/config_utils.hh, source/neuropod/internal/error_utils.hh, source/neuropod/internal/error_utils_header_only.hh, source/neuropod/internal/neuropod_tensor.cc, source/neuropod/internal/neuropod_tensor.hh, source/neuropod/internal/neuropod_tensor_serialization.cc, source/neuropod/internal/tensor_types.cc
This PR introduces a `neuropod_cc_library` rule that builds targets with `-Weverything` (+ some exceptions).
All uses of `cc_library` within `source/internal` are modified to use `neuropod_cc_library` in this PR.
Once this PR lands, we can incrementally refactor the codebase to transition all first-party `cc_*` targets to use `neuropod_cc_*` rules. At that point we can build with `-Werror` in CI to ensure that newly introduced code doesn't add warnings to the build.
Local testing + CI
=> [Build] Start enabling additional warnings

source/neuropod/internal/neuropod_tensor.cc, source/neuropod/internal/neuropod_tensor.hh, source/neuropod/internal/tensor_accessor.hh, source/neuropod/tests/test_accessor.cc
This PR adds a `view` method to `TypedNeuropodTensor<T>` that allows users to view and access a tensor as if it had a different set of dimensions.
Somewhat similar to https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view except we currently don't support `-1` dimensions. Our implementation is also simpler because all `NeuropodTensor`s are currently contiguous.
The `view` method returns a `TensorView` which is a thin wrapper around `TensorAccessor` to store strides and dimensions.
Changes made in the returned view modify the original tensor data.
`flat` is a simple method that returns a 1D view of the tensor (effectively `return view(get_num_elements())`). See https://www.tensorflow.org/api_docs/cc/class/tensorflow/tensor#flat for more details.
CI + added tests
=> Add a `view` and `flat` method to TypedNeuropodTensor

source/bazel/cc.bzl, source/neuropod/backends/BUILD, source/neuropod/backends/neuropod_backend.cc, source/neuropod/backends/python_bridge/BUILD, source/neuropod/backends/tensorflow/BUILD, source/neuropod/backends/tensorflow/tf_backend.cc, source/neuropod/backends/tensorflow/tf_tensor.cc, source/neuropod/backends/tensorflow/tf_tensor.hh, source/neuropod/backends/torchscript/BUILD, source/neuropod/backends/torchscript/torch_backend.cc, source/neuropod/backends/torchscript/torch_tensor.hh, source/neuropod/internal/backend_registration.hh
Refactor code under `source/neuropod/backends` to adhere to the stricter set of warnings introduced in #437
CI
=> [Build] Refactor backends to adhere to stricter build warnings

source/neuropod/internal/backend_registration.cc
It's not clear when the find_registered_backend method returns a null pointer, the specific reason for doing so. This change attempts to make it clear by documenting the reason why the backend isn't found.
Create a neuropod locally with required backend where we know the backend cannot be loaded. See log getting printed.
=> Added logs for situations where the backend could not be loaded

build/neuropod.dockerfile, source/neuropod/backends/python_bridge/python_bridge.cc, source/python/neuropod/backends/python/executor.py, source/python/neuropod/backends/python/packager.py, source/python/neuropod/tests/test_python_deps.py, source/python/neuropod/utils/pip_utils.py, source/python/setup.py
This PR allows python/pytorch models to specify their python dependencies at packaging time. These dependencies are used to generate a `requirements.lock` file that is stored within the model.
When loading a python model, if a requirements.lock file is found, the dependencies are automatically installed into `~/.neuropod/pythonpackages/py{MAJOR_VERSION}{MINOR_VERSION}/` (if they don't already exist).
These python packages are installed in a way where we can independently load each python package we want.
Added a test that packages, loads, and runs inference with a python model that requires `scikit-learn`.
=> [Python] Experimental support for specifying model dependencies

source/neuropod/internal/BUILD, source/neuropod/internal/backend_registration.cc
This PR adds some comments to the backend loading system and refactors the loading behavior to support default backends installed at absolute paths.
This helps us start to solve a few problems:
- There are a growing number of interfaces to Neuropod (C++, Python, C, Java, etc) and we don't want unique ways of installing backends per language.
- There are also issues with Java and `LD_LIBRARY_PATH` on macOS because of system integrity protection. This makes it quite difficult to use `LD_LIBRARY_PATH` to add backends for Neuropod to dlopen
-  Models can't choose the version of a framework to use. This is because all the backend `so` files for a type have the same name regardless of the version (so the backend loading system cannot load a specific version). Even if they had different names …
=> Refactor backend loading to also check absolute paths

.travis.yml, build/ci_matrix.py, source/bazel/tensorflow.bzl, source/bazel/tensorflow_hdrs.bzl, source/deps/BUILD.tensorflow
This PR enables us to run models with TF 2.2.0 on Mac (we already had TF 2.2.0 runtime support on Linux).
_Note: There are no official builds of libtensorflow for TF 2.2.0 so we're using binaries I built from source. These will be replaced with official builds from TF 2.3.0 or TF 2.4.0 once they're available. See #455 for more details._ 
CI
=> [TF] Add runtime support for TF 2.2.0 on Mac

.buildkite/pipeline.yml, build/ci/docs.sh, build/ci/install_lint_deps.sh, build/ci_matrix.py
Deploy docs every time a PR is merged to the `master` branch. Since docs are versioned (as of #460), this doesn't affect the latest stable docs.
After this PR lands, docs for `master` should be visible at https://neuropod.ai/docs/master/
Since the added functionality only works on the master branch (for security reasons), passing CI doesn't test this.
I manually ran these steps locally to ensure that docs are correctly deployed
=> [Docs] Setup automated docs deployment

build/ci/travis_build.sh, build/test.sh, build/upload_release.py
Previously, we'd only make requests to the GitHub API when doing release builds. In some cases we'd see failures when making https requests because of broken dependencies in CI. These failures would only be visible during release builds.
This PR fixes such an issue with Python 3.5 on macOS. It also enables CI pipelines to always make a request to the GitHub API so we can catch similar issues earlier. 
CI
=> [CI] Ensure we can make requests to the GitHub API from CI

source/neuropod/bindings/java/src/main/native/com_uber_neuropod_Neuropod.cc, source/neuropod/bindings/java/src/main/native/com_uber_neuropod_NeuropodTensor.cc, source/neuropod/bindings/java/src/main/native/utils.cc
Most of JNI calls may cause Java Exception that is not thrown automatically in JNI code. We already check results of calls in some cases. This change also adds ExceptionCheck where this is reasonable. If Java exception detected, we print it, clear and throw custom exception. Issue #434 
CI
=> [Java API] Add ExceptionCheck when exception is expected after JNI call

source/neuropod/bindings/java/src/main/native/com_uber_neuropod_Neuropod.cc, source/neuropod/bindings/java/src/main/native/com_uber_neuropod_NeuropodTensor.cc, source/neuropod/bindings/java/src/main/native/com_uber_neuropod_NeuropodTensorAllocator.cc, source/neuropod/bindings/java/src/main/native/com_uber_neuropod_RuntimeOptions_RuntimeOptionsNative.cc
After we enabled Clang-Tidy it reports warning on:
using namespace neuropod::jni;
because including all is a "mauvais ton". This change fixes it in one of JNI file.
CI
=> Fix some of NOLINTNEXTLINE(google-build-using-namespace)

build/build.sh, source/neuropod/BUILD, source/neuropod/bindings/java/BUILD
Fixes #468
This change modifies the dylib id of `libneuropod.so` from a bazel internal path (e.g. `bazel-out/darwin-fastbuild/bin/neuropod/libneuropod.so`) to a generic one (`@rpath/libneuropod.so`).
Previously, we were modifying all the binaries that depended on `bazel-out/.../libneuropod.so` to depend on `@rpath/libneuropod.so` instead. This required logic in multiple places and more importantly didn't fix the issue for external code that links against `libneuropod.so`
By changing `libneuropod.so` itself, we can avoid changing all the binaries and libraries that depend on it.
CI
=> Fix dylib id of libneuropod.so on macOS

build/install_python_deps.sh
The latest version of pip drops support for Python 2.7 (https://github.com/pypa/pip/issues/6148).
This PR modifies `install_python_deps.sh` to install a Python 2.7 compatible version of pip.
We should also explore dropping Python 2.7 support in the future as it's been over a year since its EOL.
CI
=> Fix pip bootstrapping on Python 2.7

tools/autofix.sh, tools/lint.sh
Use a hermetic `clang-format` binary in lint/autofix instead of a user-installed one.
_Note: this requires users to build the project at least once before using lint or autofix_
Local testing
(These are local tools and are not used in CI)
=> [Tools] Update lint and autofix to use a hermetic clang-format

build/install_python_deps.sh, source/neuropod/multiprocess/mq/ipc_message_queue.hh, source/neuropod/multiprocess/mq/ipc_message_queue_impl.hh
Fixes #395.
Previously, OPE disconnects were not catchable by user code (as an error was thrown in another thread).
This PR refactors some of the IPC message queue send and recv code to handle disconnects in a way that gives the user more control
CI
=> Allow users to catch OPE disconnect errors

source/python/neuropod/utils/pip_utils.py
When packaging a python model in some environments, a `requirements.lock` file will be generated that contains lines like `--index-url ...` and other lines that are not of the form `name==version` as expected by
https://github.com/uber/neuropod/blob/ca7e3b8b97b6ca4cb8bab0f5267bdd7f8215583f/source/neuropod/backends/python_bridge/_neuropod_native_bootstrap/pip_utils.py#L132-L136
This PR fixes the issue by adding the "--no-emit-index-url" and "--no-emit-trusted-host" flags when compling requirements.lock.
Local testing before and after this change to confirm the issue was fixed.
***Note: This description was substantially modified by @VivekPanyam  to make it more informative***
=> [Python] Add additional flags when compiling requirements.lock 

build/install_python_deps.sh
This PR updates the pip bootstrap URL in `install_python_deps.sh`.
The bootstrap script at the original URL (https://bootstrap.pypa.io/2.7/get-pip.py) prints a message asking us to update to a new one:
```
Hi there!
The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:
https://bootstrap.pypa.io/pip/2.7/get-pip.py
Sorry if this change causes any inconvenience for you!
[snip]
```
CI
=> Update pip bootstrap URL

source/neuropod/backends/python_bridge/test/BUILD, source/neuropod/backends/python_bridge/test/gpu_test_python_bridge.cc
Remove an unnecessary Python version check in a test
CI
=> Remove unnecessary version check in python bridge test

source/neuropod/backends/tensorflow/BUILD, source/neuropod/backends/tensorflow/saved_model/README.md, source/neuropod/backends/tensorflow/saved_model/constants.h, source/neuropod/backends/tensorflow/saved_model/loader.cc, source/neuropod/backends/tensorflow/saved_model/loader.h, source/neuropod/backends/tensorflow/saved_model/loader_util.cc, source/neuropod/backends/tensorflow/saved_model/loader_util.h, source/neuropod/backends/tensorflow/saved_model/reader.cc, source/neuropod/backends/tensorflow/saved_model/reader.h, source/neuropod/backends/tensorflow/tf_backend.cc, source/neuropod/backends/tensorflow/tf_backend.hh, source/neuropod/backends/tensorflow/tf_utils.cc, source/neuropod/backends/tensorflow/tf_utils.hh, source/neuropod/internal/neuropod_loader.cc, source/python/neuropod/backends/tensorflow/executor.py, source/python/neuropod/backends/tensorflow/packager.py, source/python/neuropod/backends/tensorflow/test/test_tensorflow_v2_packaging.py
This PR adds initial support for packaging and loading TensorFlow `SavedModel`s
Doing so is not entirely straightforward as described in my comment [here](https://github.com/uber/neuropod/issues/486#issuecomment-820228901).
As mentioned in that comment, we can't use TF's `LoadSavedModel` directly because of device issues with multiple TF models running in one process. As a solution, this PR pulls in the [TF 2.4 SavedModel loading code](https://github.com/tensorflow/tensorflow/tree/r2.4/tensorflow/cc/saved_model) and modifies it to handle devices correctly.
The comment linked above goes into more detail on what the modifications are and why they're needed. There is also a README file in this PR that includes a few more details. 
CI + added tests
Note: this is currently only tested with TF …
=> [TF] Add initial support for SavedModel

.github/workflows/mac_ci.yml, build/ci/gh_actions_build.sh, build/ci_matrix.py
GitHub Actions has trouble caching a folder at an absolute path so this PR moves the bazel cache for GH actions to a home-relative path.
See https://github.com/actions/cache/issues/361 for an issue that may be relevant
CI
=> Fix GitHub Actions Bazel caching

source/python/neuropod/backends/keras/test/test_keras_packaging.py, source/python/neuropod/backends/python/test/test_python_deps.py, source/python/neuropod/backends/python/test/test_python_isolation.py, source/python/neuropod/backends/python/test/test_python_packaging.py, source/python/neuropod/backends/pytorch/test/custom_ops/test_pytorch_custom_ops.py, source/python/neuropod/backends/pytorch/test/test_pytorch_packaging.py, source/python/neuropod/backends/pytorch/test/test_pytorch_strings.py, source/python/neuropod/backends/tensorflow/test/custom_ops/test_tensorflow_custom_ops.py, source/python/neuropod/backends/tensorflow/test/test_tensorflow_packaging.py, source/python/neuropod/backends/tensorflow/test/test_tensorflow_strings.py, source/python/neuropod/backends/tensorflow/test/test_tensorflow_v2_packaging.py, source/python/neuropod/backends/torchscript/test/custom_ops/test_torchscript_custom_ops.py, source/python/neuropod/backends/torchscript/test/gpu_test_torchscript_devices.py, source/python/neuropod/backends/torchscript/test/test_torchscript_packaging.py, source/python/neuropod/backends/torchscript/test/test_torchscript_strings.py, source/python/neuropod/tests/gpu_test_basic_environment_support.py, source/python/neuropod/tests/utils.py, source/python/neuropod/utils/test/test_randomify.py
This PR enables filtering python tests based on the framework they require. Tests are annotated with `@requires_framework(...)` and are skipped if the `NEUROPOD_TEST_FRAMEWORKS` environment variable is set and doesn't contain the required framework.
Local testing + https://github.com/uber/neuropod/pull/499
=> [Python] Allow filtering tests based on framework

.buildkite/pipeline.yml, .github/workflows/mac_ci.yml, build/ci_matrix.py
This PR enables us to filter tests in CI using the capabilities added in https://github.com/uber/neuropod/pull/501 and https://github.com/uber/neuropod/pull/502.
This lets us have variants in our build matrix that only test a subset of frameworks. https://github.com/uber/neuropod/pull/492 uses this to add a variant that tests just TF 2.5.0 as it requires a different CUDA and cuDNN version than the rest of our supported frameworks.
CI + https://github.com/uber/neuropod/pull/492
=> [CI] Filter tests in CI

.buildkite/pipeline.yml, .github/workflows/mac_ci.yml, build/ci_matrix.py, build/install_frameworks.py, build/neuropod.dockerfile, build/test_gpu.sh, docker-compose.test.yml, source/bazel/libtorch.bzl, source/bazel/tensorflow.bzl, source/bazel/tensorflow_hdrs.bzl, source/neuropod/internal/backend_registration.cc
This PR adds support for TF 2.5.0
CI (+ TF2 and  SavedModel tests added in #487). This PR also adds a build variant in CI that tests just TF 2.5.0 as it requires a different CUDA and cuDNN version than the rest of our supported frameworks.
=> [TF] Add support for TF 2.5.0

build/ci/gh_actions_build.sh
Remove broken `libomp` installation in Mac CI on Github Actions
CI
=> [CI] Fix libomp in Mac CI builds

README.md, docs/index.md
Add links to the Uber Eng blog post and the Spring 2021 GTC talk about Neuropod
CI (verifies that docs build successfully)
=> [Docs] Add links to blog post and GTC talk

build/test.sh, build/test_gpu.sh, source/python/neuropod/loader.py, source/python/neuropod/utils/eval_utils.py
Add a deprecation warning when loading a model from python using `_always_use_native=False`
Also changes `load_and_test_neuropod` to use the non-deprecated path by default.
CI
=> [Python] Add deprecation warning for _always_use_native=False

.buildkite/pipeline.yml, .github/workflows/mac_ci.yml, build/ci_matrix.py, docker-compose.test.yml, docs/developing.md, source/bazel/tensorflow.bzl, source/bazel/tensorflow_hdrs.bzl, source/neuropod/internal/backend_registration.cc
Keras in TF 2.6.0 broke when TF 2.7.0 was released. TF 2.6.2 fixes this (see https://github.com/tensorflow/tensorflow/releases/tag/v2.6.2 for more details). This PR replaces TF 2.6.0 with TF 2.6.2
CI
=> [TF] Replace TF 2.6.0 with TF 2.6.2

build/neuropod.dockerfile
Fix Python 3.5 builds in CI by installing libffi
CI
=> [CI] Fix Python 3.5 builds

source/neuropod/bindings/java/BUILD, source/neuropod/bindings/java/src/main/java/com/uber/neuropod/NeuropodTensor.java, source/neuropod/bindings/java/src/main/native/com_uber_neuropod_NeuropodTensor.cc, source/neuropod/bindings/java/src/test/java/com/uber/neuropod/NeuropodStringsModelTest.java, source/neuropod/bindings/java/src/test/java/com/uber/neuropod/TFStringsModelTest.java, source/neuropod/bindings/java/src/test/java/com/uber/neuropod/TorchscriptStringsModelTest.java
In neuropod JNI, it does not support STRING_TENSOR as model output. The reason is when it tries to create a Java Tensor from model output, it would check the tensor type. Only numerical tensors are supported and these tensors would be converted to ByteBuffer. However, Java NeuropodTensor itself do support STRING_TENSOR. It can get strings from the tensor data itself. Thus we refactor nativeGetBuffer method. This method would assign a null buffer to bytebuffer if it is a string tensor
Unit test
=> Support StringTensor as model output in Neuropod JNI

build/upload_release.py
Update `upload_release.py` to not upload python packages on specific builds in order to avoid uploading an artifact multiple times
CI + Test Release
=> [CI] Fix upload_release script

.buildkite/pipeline.yml, .github/workflows/mac_ci.yml, build/ci_matrix.py, docker-compose.test.yml
As described in #497 and #518, we are dropping support for old versions of frameworks that are years old and past EOL.
No use cases requiring these frameworks were identified so we will begin dropping support by turning off those builds in CI.
CI
=> Drop support for Python 2.7, 3.5 + Torch 1.1.0, 1.2.0 + TF 1.12.0, 1.13.1

build/ci/buildkite_image/README.md, build/ci/buildkite_image/create_ami.sh, build/ci/buildkite_image/get_base_ami.py, build/ci/buildkite_image/gpu_ami.json, build/ci/buildkite_image/install-nvidia-container-toolkit.sh
This PR enables us to build a buildkite CI stack AMI that has support for GPUs (drivers + container toolkit)
See https://github.com/buildkite/elastic-ci-stack-for-aws for general info on buildkite CI
- Ran a buildkite pipeline to build an AMI using `create_ami.sh` and confirmed that the resulting AMI has GPU support
- Confirmed that instances started from that AMI correctly build the rest of Neuropod
=> [CI] Add scripts to create a buildkite AMI

build/ci/install_lint_deps.sh, build/install_python_deps.sh, build/neuropod.dockerfile
Fix CI builds by upgrading the base docker image to 18.04 and running lint with py3.8.
The ppa we use to install python in our docker images recently dropped support for Ubuntu 16.04.
Also, Python 3.6 recently passed EOL so pip complains and fails during the lint build
CI
=> Fix CI: Use 18.04 base docker image + run lint w/ py3.8

.buildkite/pipeline.yml, .github/workflows/mac_ci.yml, build/ci_matrix.py, build/install_frameworks.py, docker-compose.test.yml, source/bazel/libtorch.bzl, source/deps/BUILD.libtorch, source/neuropod/backends/torchscript/torch_tensor.hh, source/neuropod/internal/backend_registration.cc
This PR adds support for Torch 1.10.2 and adds a build to the CI matrix to test it
CI
=> Add support for Torch 1.10.2

source/neuropod/backends/python_bridge/_neuropod_native_bootstrap/executor.py, source/neuropod/bindings/java/BUILD, source/neuropod/bindings/java/src/main/native/com_uber_neuropod_NeuropodTensor.cc, source/neuropod/bindings/java/src/main/native/utils.cc, source/neuropod/bindings/java/src/main/native/utils.h, source/neuropod/bindings/java/src/test/java/com/uber/neuropod/NeuropodStringsModelTest.java, source/neuropod/bindings/java/src/test/java/com/uber/neuropod/PythonStringsModelTest.java
This PR fixes how the Java bindings deal with Unicode.
Java's Unicode handling methods in JNI (e.g. `GetStringUTFChars`, `NewStringUTF`) deal with "modified UTF-8" encoding.
According to most descriptions I found online, UTF-8 and modified UTF-8 are quite similar with one of the main differences being how they deal with embedded null bytes:
- https://docs.oracle.com/javase/6/docs/api/java/io/DataInput.html#modified-utf-8
- https://en.wikipedia.org/wiki/UTF-8#Modified_UTF-8
- https://stackoverflow.com/questions/7921016/what-does-it-mean-to-say-java-modified-utf-8-encoding
Unfortunately, this does not mean that UTF-8 and modified UTF-8 are interoperable in cases without embedded null bytes. In fact, the encodings can be quite different and have different lengths.
This causes problems when …
=> Fix Unicode handling in Java bindings

source/neuropod/backends/python_bridge/_neuropod_native_bootstrap/pip_utils.py, source/python/neuropod/backends/python/test/test_preinstall_python_deps.py, source/python/neuropod/backends/python/utils.py
This PR adds a utility function called `preinstall_deps` to `neuropod.backends.python.utils`. This lets users preinstall large dependencies into Neuropod's isolated Python environments to avoid having to install these dependencies at runtime.
Added a test to verify functionality of `preinstall_deps`
=> [Python] Add utility to preinstall python deps into isolated envs

build/test.sh, build/test_gpu.sh, source/.bazelrc, source/neuropod/backends/python_bridge/python_bridge.cc
This PR modifies Neuropod to run models in isolated python environments by default. This makes it possible to have consistent model behavior between execution environments (without depending on system-installed python packages).
Using this behavior requires passing in `requirements` when packaging python models.
CI
=> Default to running models in isolated Python environments

source/WORKSPACE
Use a GitHub URL for zlib v1.2.11 instead of a zlib.net URL 
CI
=> Update zlib URL to use GitHub

build/neuropod.dockerfile
NVIDIA rotated their CUDA repo keys and that broke the CUDA docker image we depend on
See https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772
CI
=> Update CUDA repo signing keys

build/install_python_deps.sh
A major release of the `protobuf` python package ([4.21.0](https://pypi.org/project/protobuf/4.21.0/)) came out a few hours ago. It appears that `tensorflow` doesn't restrict the allowed versions of its `protobuf` dependency. This causes TF 2.2.0 to break and therefore breaks Neuropod CI.
An excerpt of the error:
```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade the protobuf package to 3.20.x or lower.
2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: …
```
=> [Python] Pin protobuf version to fix tensorflow

build/ci/docs.sh
Update `mkdocs-material` to a newer version in order to fix the docs build in CI
CI
=> [Docs] Update version of mkdocs-material

source/neuropod/backends/torchscript/torch_backend.cc, source/python/neuropod/backends/torchscript/test/test_torchscript_packaging.py
Ensures that all tensors returned from a TorchScript model are contiguous.
Fixes #553
Added a test. The test did not pass before the fix and it does pass after the fix.
=> Ensure TorchScript output tensors are contiguous

source/python/neuropod/backends/python/packager.py, source/python/neuropod/backends/python/test/test_python_packaging.py, source/python/neuropod/utils/config_utils.py, source/python/neuropod/utils/packaging_utils.py
When packaging a model, write a `manifest.json` file listing all packaged files along with their sha256 hashes.
CI + local testing + added test to ensure the manifest is correct
=> Write a manifest when packaging models
